# Define the order and layout of your prompt
format = """$all$fill$time$line_break$character"""

[directory]
truncation_length = 0
truncate_to_repo = false
style = "cyan"

[time]
disabled = false
format = " [$time]($style)"
style = "yellow"
time_format = "%T" # Standard 24-hour format (HH:MM:SS)

[fill]
symbol = "─"
style = "green"

[nodejs]
disabled = true

[bun]
disabled = true

[java]
disabled = true

[c]
disabled = true

[python]
disabled = true

[custom.jj]
when = "jj-starship detect"
format = "$output "
shell = ["jj-starship", "--no-symbol", "--no-git-id", "--no-jj-id"]

[git_commit]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true
