[nodejs]
disabled = true

[bun]
disabled = true

[java]
disabled = true

[python]
disabled = true

[custom.jj]
when = "jj-starship detect"
format = "$output "
shell = ["jj-starship", "--no-symbol", "--no-git-id"]

[git_commit]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true
